### ISSUE TITLE
Unused File References

### ISSUE THREAD

**Issue by ardatdev** [Artado-Project/artadosearch#25]
There are still many references to "main.js" file which has been deleted with [this PR](https://github.com/Artado-Project/artadosearch/pull/12). Those references should be deleted. An example: https://github.com/Artado-Project/artadosearch/blob/f4a48a59cd2bf66a548cb63a463cd5b1b6d8f161/artadosearch/Default.aspx#L20

**Comment by Arnolxu** [comment]
Solved in 862e7023d7d84cec561de28a18df507d9efb876c
