### ISSUE TITLE
Some icons are not working

### ISSUE THREAD

**Issue by ardatdev** [Artado-Project/artadosearch#26]
I noticed that an icon in mobile settings page(top left corner) is not working. There might be a problem with Feather Icons. Screenshot:
![image](https://github.com/Artado-Project/artadosearch/assets/47920304/a5770293-242d-4d3c-9130-a9efdd9496dd)

**Comment by Arnolxu** [comment]
Seems like a problem with `/node_modules/feather-icons/dist/feather.min.js`.
![resim](https://github.com/Artado-Project/artadosearch/assets/79412062/c3778d01-80d7-4ecd-9794-0b5a344fc6e0)
I'll try updating `node_modules` in the host.

**Comment by Arnolxu** [comment]
Seems to be fixed in 12a211a991c420403f8cfa948f2011eb43e941aa
