### ISSUE TITLE
We don't have a donation page

### ISSUE THREAD

**Issue by ardatdev** [Artado-Project/artadosearch#31]
There is a link to donations page in settings but we don't have that page.

**Comment by LinuxUsersLinuxMint** [comment]
> There is a link to donations page in settings but we don't have that page.

Then you can create a Donation page or delete the page link. But I'm sorry I can't help with that. @ardatdev

**Comment by LinuxUsersLinuxMint** [comment]
https://github.com/Artado-Project/artadosearch/issues/30#issuecomment-1779958106 @ardatdev

**Comment by yasinldev** [comment]
The donation page was included in the existing rewrite branch with the last commit. Please see #47 and [0f91c2f](https://github.com/Artado-Project/artadosearch/commit/0f91c2f50b96e4d88b85ebbd709bf362e8366c3c)
