### ISSUE TITLE
Cause 'package.json' has been modified, npm encounters an error while installing packages.

### ISSUE THREAD

**Issue by yasinldev** [Artado-Project/artadosearch#49]
Some package.json files were removed with the last commit. Please don't do anything on your own, these packages are automatically generated by the framework, in case of missing or excess packages use the following command. 
```
npm prune
```

Error:
<img width="676" alt="image" src="https://github.com/Artado-Project/artadosearch/assets/90653146/5fdcad49-515b-4170-8a9a-6bf60d6b4c63">

**Comment by ardatdev** [comment]
Please don't make assumptions without understanding the issues. As you can see in the last commit's changes I didn't remove any frameworks or packages. Instead I upgraded some of them and added new ones. It looks like you don't have the necessary packages. You should install them with `npm install` . Also I haven't run the `npm prune`.

**Comment by yasinldev** [comment]
I got this error when trying to install packages directly with the last commit, please check the package.json file

**Comment by yasinldev** [comment]
error resolved with last commit
