### ISSUE TITLE
I can't make the dark mode design of the current version

### ISSUE THREAD

**Issue by yasinldev** [Artado-Project/artadosearch#51]
I am trying to make the dark mode design of the current version, but after a certain period of time, the changes I have made in the design do not work. I tried over and over again but I couldn't do it, I need people who have any ideas or who can do it, can contributors help with this problem?

**Comment by islekcaganmert** [comment]
Which dark mode approach you are trying to? I've always used @media(prefers-color-scheme: dark) and never ran into problems with any browser.

**Comment by yasinldev** [comment]
> Which dark mode approach you are trying to? I've always used @media(prefers-color-scheme: dark) and never ran into problems with any browser.

hello can you please share screenshots of the version in dark mode? maybe it's a problem with my browser setting

**Comment by islekcaganmert** [comment]
Artado's dark mode is also not working on me. This is presumably not a browser issue. As I said I've always used prefers-color-scheme in HereUS and never ran into issues, and this approach is also automatic.

As HereUS UI is open source now, you can take a look on: https://github.com/hereus-pbc/hereus-ui-3.1

**Comment by yasinldev** [comment]
Existing components need to be manually switched to dark mode to be compatible with other frameworks, I will solve the dark mode problem soon

**Comment by yasinldev** [comment]
the issue solved with last commit. Please see [last commit](https://github.com/Artado-Project/artadosearch/commit/3cb2345ac9aa8bac8293b251c17ab34eee4287ee)
