### ISSUE TITLE
All search attempts failing

### ISSUE THREAD

**Issue by islemci** [Artado-Project/artadosearch#53]
**Describe the bug**
Searching anything on the site, leads to an error.

**To Reproduce**
1. Go to the [main page](https//artadosearch.com)
2. Type anything
3. Click search
4. App throws error

**Expected behavior**
Search is done, and user gets a list of the results.

**Screenshots**
<img width="1398" alt="Screenshot 2024-10-20 at 19 41 33" src="https://github.com/user-attachments/assets/51bde8aa-ee13-4518-8ed0-0feece17149e">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6
 - Browser: Firefox
 - Version: Firefox 131.0.3

**Comment by ardatdev** [comment]
We changed our servers' IP this morning but apparently forgot to change the connection strings in Web.config. This issue is now fixed.
