### ISSUE TITLE
XSS Bug Report

### ISSUE THREAD

**Issue by bugresearch** [Artado-Project/artadosearch#54]
**Describe the bug**
Reflected XSS vulnerability has been detected in Izlesene search results of Artado search engine.

**Example Payload**
" onclick="alert(1)" alt="test

**To Reproduce**
1. The above payload should be searched in a search engine.
2. Then select Izlesene from the search categories.
3. You can click on any search result for DOM XSS to work.

**Expected behavior**
In order to ensure the security of all users using the search engine, the relevant XSS vulnerability must be closed.

**Comment by ardatdev** [comment]
This bug must have been solved with [this commit](https://github.com/Artado-Project/artadosearch/commit/dc1175d59d569d89dc4671ca14201dd8457d4ead). Can you confirm?

**Comment by bugresearch** [comment]
Yes it's fixed. But there are too many xss vulnerabilities

**Comment by ardatdev** [comment]
With this commit most of them should be fixed. If you find any more of them, please open an issue.

**Comment by islemci** [comment]
@ardatdev, i think there should be a private and more secure way (like a security@artado.xyz) to disclose critical bugs and security breaches like this.

https://www.cisa.gov/vulnerability-disclosure-policy-template

edit1: Publicly mentioning security vulnerabilities is a REALLY dangerous action.

**Comment by ardatdev** [comment]
Everyone can reach me from arda@artadosearch.com
