### ISSUE TITLE
Add (Optinoal) Don't Show Malicous And Phishing Websites In Results

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [Artado-Project/artadosearch#7]
You can use my database for that.

**Comment by ardatdev** [comment]
Can you share your database? Maybe we can do this as a extension.

**Comment by HydraDragonAntivirus** [comment]
https://mega.nz/folder/n85EkQwa#6E6xSXO5Y2NQ4rzrg-nIzA

**Comment by HydraDragonAntivirus** [comment]
https://github.com/HydraDragonAntivirus/Hydra-Dragon-Antivirus-Linux

**Comment by Arnolxu** [comment]
Thanks a lot for these databases! We'll have a look at them, but our current priority is to fix bugs, typos and design mistakes.
