### ISSUE TITLE
Eklenti, tema ve diğer şeyler hk.

### ISSUE THREAD

**Issue by tem1z** [Artado-Project/artadosearch#9]
Eklenti ve tema yayınlayacaklar için daha detaylı bir bilgilendirme yazısı hazırlansa iyi olur. Ek olarak taslak kısmı gelmeli ve oradan test edebilmeliyiz. Ayrıca örneğin tüm bilgileri doldurup bir temayı kaydet dediğimiz zaman hata mesajı veriyor ancak ne kadar fazla gönder yani kaydet derseniz o kadar fazla hata mesajı ile projeyi kaydediyor. Bir de başvuru kısmı var. Temalar ve eklentiler yayınlanacağı zaman sanırım başvuru sürecine giriyor. Bu başvuru sürecinde iken başvuru düzenlenemezse bile en azından başvuruyu yapan başvuruyu taslak olarak kaydedebilir ya da direkt iptal edip silebilir. Keza kaydet kısmında da sil diye bir seçenek yok zaten kaydet ne anlama geliyor onu bile bilmiyorum çünkü doğru dürüst bir açıklama yapılmamış. Bir de yenileme kısmı var. Mesela eklenti ya da tema içi kaydet butonuna tıkladığında her yenilemede sayfayı tekrar ve tekrar kaydediyor.

Açıklama metinleri geliştirilmeli ve daha anlamlı hale getirilmeli, görsel uyarılar artırılmalı bence. Zira birçok noktada hata var. Örneğin açıklama kısmı zorunlu ancak diğerleri gibi * yok keza yine kaynak kısmı da var. Kaynak kısmı var ama ne kaynağı belirtilmemiş. Bir yere mi yükleyeceğiz, github'a mı yükleyeceğiz belirtilmemiş. Zorunlu mu değil mi belirtilmemiş. 

Daha birçok eksik kısmı var ama şu anda yazabildiklerim bunlar. Projeyi izlemeye devam edeceğim, başarılar.

**Comment by ardatdev** [comment]
Başvuruyu zaten taslak olarak kaydetme var. Kaydet butonu o işe yarıyor. Yayınla butonu ise başvuru olarak gösteriyor. Bunların dışında zaten Developers panelini yeniden yazmayı planlıyoruz. Ayrıca bu issue bura için uygun olmamış. Developers panelinin kendi [github](https://github.com/Artado-Project/devs) adresi var fakat sorun değil. Ayrıca issue'larda İngilizce yazmaya dikkat edersek güzel olur.

Desteğiniz ve görüşleriniz için teşekkürler.
